### ISSUE TITLE
Enable shuffle filter

### ISSUE THREAD

**Issue by richli** [georust/netcdf#100]
The [`nc_def_var_deflate()`](https://docs.unidata.ucar.edu/netcdf-c/current/group__variables.html#ga59dad3301f241a7eb86f31b339af2d26) function has an argument to enable the HDF5 shuffle filter, which sometimes help improve compression ratios.

This function is called by the `compression()` method for a `VariableMut` and currently, the `shuffle` value is hard-coded to `false`. Could this setting be exposed? For example:

```rust
pub fn compression(&mut self, deflate_level: nc_type, shuffle: bool) -> Result<()> {}
```

**Comment by magnusuMET** [comment]
That sounds like a great idea. Would you like to open a PR implementing this?

**Comment by lnicola** [comment]
If we're (well, you're) breaking the API anyway, should this be something like `.compression(Compression::deflate().level(6).shuffle(false))`?

It looks like other compression methods are available (like blosc), but not supported in the bindings.

**Comment by magnusuMET** [comment]
That could be a good way to do it. I would like to revamp the API as `netcdf-c` has gotten multiple filters now, maybe we should have a `VariableBuilder`?

**Comment by richli** [comment]
Yes, I'd be open to submitting a PR for the simple change, but I don't have time right now for something more involved like the API for a `VariableBuilder`. But I agree that's the way to go!

**Comment by magnusuMET** [comment]
I am OK with breaking changes, there is quite a lot of unreleased code since v0.7.0 which requires more substantial updates for the library users. A quick and dirty fix by making `compression` take the shuffle is more than enough for now
