### ISSUE TITLE
Can support wasm32?

### ISSUE THREAD

**Issue by XC-Zero** [georust/netcdf#161]
I want to build wasm , but netcdf use libc, which maybe not support wasm32? How can i do o(╥﹏╥)o ?

![Snipaste_2024-12-16_15-06-34](https://github.com/user-attachments/assets/7ef40584-6342-453c-bfb3-ca38819fed7b)

**Comment by magnusuMET** [comment]
The biggest issue will be to build `netcdf-c`. This will require a substantive amount of work

**Comment by XC-Zero** [comment]
fine , thank u~
