### ISSUE TITLE
Opening a gitter.im room ?

### ISSUE THREAD

**Issue by lwandrebeck** [georust/netcdf#34]
Everything’s in the title !
It’d be nice to be able to chat in real-time about dev, and support, imho.

**Comment by magnusuMET** [comment]
Would it be an option to use the GeoRust discord chat?

**Comment by lwandrebeck** [comment]
Why not. I must admit having nothing to install, and being just a click away from chat is nice, but if people prefer discord, then so be it :)

**Comment by magnusuMET** [comment]
As it is just me at the moment working on this crate I will close this issue. Feel free to open an issue if there are any items you would like to discuss
