### ISSUE TITLE
Parallel read

### ISSUE THREAD

**Issue by gauteh** [georust/netcdf#42]
Hi, I think both netcdf and hdf5 supports parallel reads. Glimpsing at the source of this project there seem to be some global locks. Is parallel netcdf supported? 

I am interested in the raw xdr encoded data for a dap server. Is it possible to access the raw bytes through this library?

**Comment by magnusuMET** [comment]
The standard netcdf library on Ubuntu machines do not come with parallel support, so this is not supported as of now. The global lock acts to serialize all access to the (not threadsafe) netcdf c library, but this restriction could be lifted for the parallel reads.

**Comment by magnusuMET** [comment]
The underlying netcdf library does not support accessing the raw bytes, so this is not exposed here either.

**Comment by gauteh** [comment]
I do not know the extent of the thread-un-safety of libnetcdf. Is, for instance, regular netcdf safe to use from several threads _as long as_ as the same file handle is only used from one thread at the time? So that by opening the same file twice it can be used from two threads concurrently? In that case the lock can be moved down to `netcdf::File` level, at least for reads. This would speed things up considerably for my purpose. Especially if `Clone` could be implemented in such a way that all the metadata does not need to be re-generated and stored twice (maybe CoW?). By opening a new file at each Clone that might be possible.

**Comment by gauteh** [comment]
Just for reference, removing the LOCK.lock in values_to and stress-testing with concurrent reads causes `Error 11: Resource temporarily unavailable`.

**Comment by magnusuMET** [comment]
Parallell reads/writes goes through pnetcdf. I think this issue can focus on strictly the parallell functionality, which requires opening through `nc_{create/open}_par`

**Comment by magnusuMET** [comment]
> Just for reference, removing the LOCK.lock in values_to and stress-testing with concurrent reads causes `Error 11: Resource temporarily unavailable`.

This is errno EAGAIN

**Comment by AntoineRenaud91** [comment]
Is there any update on this issue or is it a core limitation of the libnetcdf underlying lib ?  I have red somewhere that the zarr format is gaining popularity because of this.

**Comment by magnusuMET** [comment]
It is still a problem with `libnetcdf` and is not likely to be resolved anytime soon. There has been some progress on [hidefix](https://github.com/gauteh/hidefix) which allows one to bypass netcdf and read in parallel. I recommend checking out that project and asking/opening issues for your usecase there.

**Comment by gauteh** [comment]
I added some convenient methods for indexing a NetCDF file so that you are able to read it using hidefix quickly. Not much to it, but might make it easier to see how to glue it together: https://github.com/gauteh/hidefix/pull/29

```
use hidefix::prelude::*;

let i = netcdf::open("tests/data/coads_climatology.nc4").unwrap().index().unwrap();
let iv = i.reader("SST").unwrap().values::<f32>(None, None).unwrap();
```

**Comment by AntoineRenaud91** [comment]
Thanks for the suggestions !

**Comment by AntoineRenaud91** [comment]
How hard would it be to add bindings to the [nc_open_par](https://docs.unidata.ucar.edu/netcdf-c/current/group__datasets.html#ga019098e9d5265006a11c9a841eb81b74) function ?

Would it resolve this issue ?

**Comment by lnicola** [comment]
That one's for MPI, which is not threads. I don't know if you want MPI, or if it's even supported.
