### ISSUE TITLE
codecov and coveralls coverage broken

### ISSUE THREAD

**Issue by lwandrebeck** [georust/netcdf#57]
Hi,

coverage badges are broken due to org change. Could someone from georust take a look ? (logging in codecov and coveralls and adding repo should be enough)

Thanks,

**Comment by magnusuMET** [comment]
I tried rerunning Travis, which gave us the codecov badge back. There seems to be some form of failure for `kcov`, resulting in

```
error: failed to parse lock file at: /home/travis/build/georust/netcdf/Cargo.lock

Caused by:

  invalid serialized PackageId for key `package.dependencies`
```
