### ISSUE TITLE
Hash of file changes after opening with rust-netcdf

### ISSUE THREAD

**Issue by apexys** [georust/netcdf#65]
Hey everyone,
we've been using this library for a while now at GEOMAR and we've noticed that apparently in some cases the (SHA1-)hash of the file we've opened with the library changes, even though we are just reading from it.
Is this due to some file-locking-flag in the file itself or is it some other problem?
We've also had our application crash for unrelated reasons a few times and ended up with corrupted netCDF-files we were reading from, which refused to be opened for one launch, but worked fine again on the next launch.
Sadly most of the files we've been using are way to big to ever attach them here, but for example this happened with a checkout of the GEBCO-2019-dataset.
Any idea why this could be happening?
Thanks in advance!

**Comment by magnusuMET** [comment]
Hi @apexys. That sounds like a very bad issue! This library opens files using `NC_NOWRITE` when using `netcdf::open`, so such behaviour is definitely unexpected! It looks like we have to find a MRE and report this upstreams to `netcdf-c`.

What version of `hdf5`, `netcdf-c`, and this crate are you using? Any access patterns or behaviours which exacerbates the errors? Are you using the `hdf5` or `hdf5-sys` crates? Are you using multithreading?

**Comment by magnusuMET** [comment]
I don't think `hdf5` got a lock inside the file, it seems to require this from the operating system. I've attempted to replicate using the GEBCO 2020 dataset and using `std::process::abort` to terminate the program in various places, but no success as of yet.

`hdf5` and `netCDF` does not have any mechanisms to fix corruption, so it is very strange that it should not work for one launch and work for the next. Could there be some hardware errors? Faulty RAM?

**Comment by apexys** [comment]
Thinking about this further, the file was on an NTFS disk on a Windows 7 machine, so we think it might just be a problem with that system. 
For some reason though, the "created" / "last accessed" date is set to the last time the file is "fixed" and the "last changed" date is some time in 2019 which seems plausible. 
Weird happnenings. 
I'll update this thread when this happens again, we didn't manage to reproduce this issue on Windows 10 or Ubuntu 18.04.
